### ISSUE TITLE
FastITPN checkpoints

### ISSUE THREAD

**Issue by kangben258** [sunsmarterjie/iTPN#14]
I would like to ask, is the resolution used for fine-tuning on 21k here 512? The weight here seems to provide a resolution of 224
![2024-04-14 14-18-21 的屏幕截图](https://github.com/sunsmarterjie/iTPN/assets/80822793/e2d56113-06b4-4643-ae48-a8a4d1f8d856)

**Comment by sunsmarterjie** [comment]
We intermediate fine-tune Fast-iTPN-B on 21k using 224x224 inputs and then fine-tune on 1k using 512x512. This is commonly used setting.

**Comment by kangben258** [comment]
Thanks for your reply!
