### ISSUE TITLE
Great Work！ Some issue.

### ISSUE THREAD

**Issue by ElliottZhen** [sunsmarterjie/iTPN#16]
你好~
当我使用使用iTPN-B作为我下游任务的Backbone时，我下载您提供的itpn-base-pixel.pth作为预训练权重，没有任何问题，但是当我使用fast_itpn中modeling_finetune的fast_itpn作为backbone，并下载fast_itpn_base_clipl_e1600.pt作为预训练权重加载时，发现几乎所有模块的参数都missing了，请问您知道为什么吗？
因为我之前用的预训练权重都是pth结尾，不知道是不是因为fast是pt的原因。
@sunsmarterjie

**Comment by sunsmarterjie** [comment]
xformer中的算子：import xformers.ops as xops  ---> fast-itpn当前版本没有使用，可以忽略
