### ISSUE TITLE
fast_itpn

### ISSUE THREAD

**Issue by ElliottZhen** [sunsmarterjie/iTPN#17]
你好，
我将您的fast_itpn作为骨干网络，用到我的下游任务，加载预训练权重时候，发现缺失了很多东西.
mask_token, align_dim_16tofpn, lm_hewad.weight， decoder开头的等等，
还有就是几乎所有的block都有这个缺失，类似于block.1.gamma_1, block.1.gamma_2

请问这正常吗？
非常感谢您。
@sunsmarterjie

**Comment by sunsmarterjie** [comment]
log文件发来看看

**Comment by sunsmarterjie** [comment]
关于Fast-iTPN的性能，我几乎可以断定是哪里出了问题，因为我们的实验不会出现这种情况，等我明天回复您。
关于iTPN的其他版本，我们训的最小模型就是base。
谢谢



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年07月13日 22:01 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [sunsmarterjie/iTPN] fast_itpn (Issue #17) |

因为我看到您Fast_iTPN的small，tiny，base都发布了预训练权重，到时候想几个版本都跑一下，iTPN反正已经有用，不知道您当时训iTPN的small、tiny版本了没。
这个Fast_iTPN第一轮刚开始几十个迭代损失比iTPN好，因为收敛慢，越来越差。

**Comment by sunsmarterjie** [comment]
Hi，我更需要加载模型输出的日志内容哈。现在您提供的信息很难判断哪里出了问题

**Comment by sunsmarterjie** [comment]
1. 看起来没有设置gamma，即模型的init_values，可以初始化为0.1, 然后就会加载； 2. ”mask_token, align_dim_16tofpn, lm_hewad.weight， decoder开头“这些缺失是正常的，因为这是预训练使用的模块； 3. 你的训练超参是什么？

**Comment by sunsmarterjie** [comment]
有什么好消息请让我知道

**Comment by sunsmarterjie** [comment]
目前的fast-itpn没有使用加速操作，是当做基础backbone使用的，所以速度慢是正常的



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年07月27日 16:05 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [sunsmarterjie/iTPN] fast_itpn (Issue #17) |

你好，我最近两周做了一些实验，Fast-iTPN的效果确实比iTPN好一些，当我进行效率分析时发现，Fast-iTPN-B比iTPN-B的macs和params少，尤其是params少了13M左右，但是在FPS方面Fast-iTPN-B比iTPN-B慢大约10FPS左右，我不清楚这是否正常，或者您有什么建议吗？
@sunsmarterjie
