### ISSUE TITLE
Question about using iTPN as downstream pre-train backbone.

### ISSUE THREAD

**Issue by ai-application** [sunsmarterjie/iTPN#18]
Hi 
   Nice and amazing work for me. I want use the iTPN for my downstream segmentation task, serve as the fixed parameter backbone for pyramid feature extraction. When I load the checkpoint as author's code in [run_class_finetuning.py](https://github.com/sunsmarterjie/iTPN/blob/main/fast_itpn/run_class_finetuning.py). I meet the following warnings:
![image](https://github.com/user-attachments/assets/24eb180d-e4dd-4b07-86d5-cff22b1c61a7)
Dose these warnings will affect the feature extraction during my network? Thanks a lot.

**Comment by sunsmarterjie** [comment]
Thanks! No, these parameters are used only for pre-training, and will not affect the finetuning.
