### ISSUE TITLE
Could you please provide the weight of another of your works HiViT?

### ISSUE THREAD

**Issue by shi-lt** [sunsmarterjie/iTPN#5]

**Comment by sunsmarterjie** [comment]
base: https://drive.google.com/file/d/1VZQz4buhlepZ5akTcEvrA3a_nxsQZ8eQ/view
code: https://github.com/zhangxiaosong18/hivit

**Comment by shi-lt** [comment]
Thank you very much. It would be even better if you could provide the Small and Tiny versions.

**Comment by sunsmarterjie** [comment]
hivit small supervised: https://drive.google.com/file/d/1bXr6089pbygItoVGBPbLhlRkdXG11NrT/view?usp=share_link

**Comment by shi-lt** [comment]
Thank you very much for your timely reply. But this is the weight of fully supervised training, and what I want to use is the weight trained using MAE.

**Comment by sunsmarterjie** [comment]
We do not pre-train small size model using MAE.  Among various methods and models, small self-supervised pre-training models are not as good as fully supervised ones.



---- Replied Message ----
| From | ***@***.***> |
| Date | 04/12/2023 19:15 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [sunsmarterjie/iTPN] Could you please provide the weight of another of your works HiViT? (Issue #5) |

Thank you very much for your timely reply. But this is the weight of fully supervised training, and what I want to use is the weight trained using MAE.

**Comment by shi-lt** [comment]
Thank you very much for your answer.
